[package]
name = "anime-game-core"
version = "2.0.0"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/an-anime-team/anime-game-core"
edition = "2021"

[features]
network = ["dep:minreq"]

default = ["network"]

[dev-dependencies]
blake3 = "1.4.1"

[dependencies]
flume = "0.11.0"
thiserror = "1.0.47"
lazy_static = "1.4.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# network

minreq = { version = "2.8.1", features = ["json-using-serde", "proxy", "https"], optional = true }

# filesystem drivers

uuid = { version = "1.4.1", features = ["fast-rng"] }

md-5 = { version = "0.10.5", features = ["asm"] }
